# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8655b7acdb4923d99753883f23782892f29a6b675af4050151d20b5324098b85e27d25f0c812f20c4174251714e73f124ef2339e7f12e47dec11529d86f135

test:
  secret_key_base: 449a15f12aa70f1d2fc1013c36d34fcdd40105faef843ec4801d76435b39e19799db68c5dfb6541d29a132e28298fe78663829a46392825d971209ecf0f8d941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
